"""Leakage-safe event response datasets and conservative causal estimators."""

from aegisquant.research.causal.contracts import (
    DEFAULT_CAUSAL_DIAGNOSTIC_POLICY,
    CausalDiagnosticPolicy,
    CausalDiagnostics,
    CausalEffectEstimate,
    CausalEstimand,
    CausalMethod,
    CausalPointEstimate,
    CovariateBalanceReport,
    DoublyRobustObservation,
    DoublyRobustSpec,
    EventResponseDataset,
    EventResponseRow,
    EventStudySpec,
    HistoricalState,
    IdentificationStatus,
    MatchedControl,
    MatchedStateSet,
    MatchingSpec,
    PlaceboKind,
    PlaceboTestResult,
    PreTreatmentFitReport,
    PreTrendReport,
    PropensityOverlapReport,
    StateWeight,
    SyntheticControlResult,
    SyntheticControlSpec,
    build_causal_effect_estimate,
    build_event_response_dataset,
)
from aegisquant.research.causal.diagnostics import (
    assemble_causal_diagnostics,
    covariate_balance_report,
    pre_treatment_fit_report,
    pretrend_report,
    propensity_overlap_report,
)
from aegisquant.research.causal.event_study import estimate_matched_event_study
from aegisquant.research.causal.matching import match_historical_states
from aegisquant.research.causal.placebo import (
    evaluate_placebo_distribution,
    treatment_permutation_placebo,
)
from aegisquant.research.causal.synthetic_control import fit_synthetic_control
from aegisquant.research.causal.uplift import estimate_aipw

__all__ = [
    "DEFAULT_CAUSAL_DIAGNOSTIC_POLICY",
    "CausalDiagnosticPolicy",
    "CausalDiagnostics",
    "CausalEffectEstimate",
    "CausalEstimand",
    "CausalMethod",
    "CausalPointEstimate",
    "CovariateBalanceReport",
    "DoublyRobustObservation",
    "DoublyRobustSpec",
    "EventResponseDataset",
    "EventResponseRow",
    "EventStudySpec",
    "HistoricalState",
    "IdentificationStatus",
    "MatchedControl",
    "MatchedStateSet",
    "MatchingSpec",
    "PlaceboKind",
    "PlaceboTestResult",
    "PreTreatmentFitReport",
    "PreTrendReport",
    "PropensityOverlapReport",
    "StateWeight",
    "SyntheticControlResult",
    "SyntheticControlSpec",
    "assemble_causal_diagnostics",
    "build_causal_effect_estimate",
    "build_event_response_dataset",
    "covariate_balance_report",
    "estimate_aipw",
    "estimate_matched_event_study",
    "evaluate_placebo_distribution",
    "fit_synthetic_control",
    "match_historical_states",
    "pre_treatment_fit_report",
    "pretrend_report",
    "propensity_overlap_report",
    "treatment_permutation_placebo",
]
