"""Leakage-safe temporal validation, robust statistics, holdout, and stresses."""

from aegisquant.research.validation.holdout import (
    FinalHoldoutVault,
    HoldoutAuditEntry,
    HoldoutState,
    ResearchFreezeManifest,
    create_freeze_manifest,
)
from aegisquant.research.validation.leakage import (
    FeatureAccessRecord,
    FeatureSourceKind,
    LabelWindowRecord,
    LeakageAuditReport,
    NormalizationScope,
    assert_no_leakage,
    audit_leakage,
)
from aegisquant.research.validation.splits import (
    CombinatorialFold,
    SampleSpan,
    TemporalFold,
    TemporalSplitPolicy,
    WalkForwardMode,
    combinatorial_symmetric_splits,
    walk_forward_splits,
)
from aegisquant.research.validation.statistics import (
    MultipleTestingReport,
    PBOResult,
    SharpeInference,
    benjamini_hochberg,
    deflated_sharpe_ratio,
    probabilistic_sharpe_ratio,
    probability_of_backtest_overfitting,
)
from aegisquant.research.validation.stress import (
    CostStressResult,
    EconomicPeriod,
    EventLatencyScenario,
    Regime,
    RegimeObservation,
    RegimeSlice,
    apply_cost_stress,
    engagement_as_of_with_delay,
    event_latency_scenarios,
    parameter_perturbations,
    point_in_time_regime_slices,
)

__all__ = [
    "CombinatorialFold",
    "CostStressResult",
    "EconomicPeriod",
    "EventLatencyScenario",
    "FeatureAccessRecord",
    "FeatureSourceKind",
    "FinalHoldoutVault",
    "HoldoutAuditEntry",
    "HoldoutState",
    "LabelWindowRecord",
    "LeakageAuditReport",
    "MultipleTestingReport",
    "NormalizationScope",
    "PBOResult",
    "Regime",
    "RegimeObservation",
    "RegimeSlice",
    "ResearchFreezeManifest",
    "SampleSpan",
    "SharpeInference",
    "TemporalFold",
    "TemporalSplitPolicy",
    "WalkForwardMode",
    "apply_cost_stress",
    "assert_no_leakage",
    "audit_leakage",
    "benjamini_hochberg",
    "combinatorial_symmetric_splits",
    "create_freeze_manifest",
    "deflated_sharpe_ratio",
    "engagement_as_of_with_delay",
    "event_latency_scenarios",
    "parameter_perturbations",
    "point_in_time_regime_slices",
    "probabilistic_sharpe_ratio",
    "probability_of_backtest_overfitting",
    "walk_forward_splits",
]
