"""Generate and verify deterministic event, configuration, and data JSON Schemas."""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from pydantic import BaseModel

from aegisquant.accounting.models import (
    AccountingInstrument,
    CashflowEvent,
    ChartOfAccounts,
    DailyLedgerSnapshot,
    EntryTemplate,
    EquitySnapshot,
    LedgerRecord,
    PnLBreakdown,
    PositionLotState,
    ReconciliationCase,
    SettlementEvent,
    ValuationSnapshot,
    VenueAccountSnapshot,
)
from aegisquant.backtest.models import (
    BacktestFill,
    BacktestOrder,
    BacktestResult,
    BacktestRunSpec,
    CostSchedule,
    HistoricalInstrumentRule,
    MarginPolicy,
    StressScenario,
)
from aegisquant.backtest.policy import BacktestPolicy
from aegisquant.canary_readiness import (
    BinanceTestnetRunEvidence,
    ExternalAlertDeliveryReceipt,
    P12CanaryReadinessAssessment,
    P12EvidenceAttestation,
    P12EvidenceBundle,
    P12GateResult,
    P12ReadinessPolicy,
    ProtectedTimestampReceipt,
    TestnetReconciliationReceipt,
    TestnetRiskAuthorizationReceipt,
)
from aegisquant.config.models import AppConfig
from aegisquant.data.archive import RevisionRecord, TombstoneRecord
from aegisquant.data.catalog import CatalogEntry
from aegisquant.data.checkpoint import IngestCheckpoint
from aegisquant.data.lineage import TransformationLineage
from aegisquant.data.market import (
    CanonicalAsset,
    CanonicalExposure,
    CanonicalPair,
    ClockObservation,
    ComparisonResult,
    LeadLagObservation,
    MarketObservation,
    UnifiedInstrument,
)
from aegisquant.data.models import (
    ContentTimeSemantics,
    DatasetManifest,
    ImportProposal,
    InventoryRecord,
    ProviderRegistryDocument,
    QualityReport,
)
from aegisquant.data.providers.binance.adapter import (
    DatasetDescriptor,
    ProviderHealth,
    ProviderQuota,
)
from aegisquant.data.providers.binance.changelog import ChangelogSnapshot
from aegisquant.data.providers.binance.models import (
    BookTickerRecord,
    ConnectionHealth,
    DepthDeltaRecord,
    FundingRateRecord,
    InstrumentSnapshot,
    KlineRecord,
    MarkIndexRecord,
    OpenInterestRecord,
    RawResponseEnvelope,
    SoakEvidence,
    SoakStreamEvidence,
    TradeRecord,
)
from aegisquant.data.providers.binance.replay import FixtureEnvelope, FixtureManifest
from aegisquant.data.providers.public import (
    BookUpdate,
    PublicRequest,
    WsSubscription,
)
from aegisquant.data.providers.public import (
    ChangelogSnapshot as PublicChangelogSnapshot,
)
from aegisquant.decision import (
    DirectionalForecastDistribution,
    DirectionalForecastScenario,
    EventDirectionalAlpha,
    EventRiskOverlay,
    ExecutionCostDistribution,
    ExecutionCostModelV2,
    ExecutionCostScenario,
    IntegratedDecisionReport,
    NetEdgeDistribution,
    NetEdgePolicy,
    NetEdgeScenario,
    NoTradeDecision,
    ReplayQueueInputs,
    RiskOverlayPolicy,
)
from aegisquant.domain.accounting import JournalEntry, PositionLot
from aegisquant.domain.execution import Fill, OrderCommand, OrderIntent, VenueOrder
from aegisquant.domain.intelligence import (
    AlphaSignal,
    ClaimRecord,
    EngagementSnapshot,
    EventCluster,
    EventImpactForecast,
    ForecastBundle,
    MarketEvent,
    PortfolioProposal,
    RawContentEnvelope,
    RiskDecision,
    SourceIdentity,
)
from aegisquant.domain.policy import SourceProcessingPolicy
from aegisquant.domain.serialization import EventEnvelope
from aegisquant.domain.truth import (
    AtomicClaim,
    EvidenceRetrievalHit,
    EvidenceSearchPlan,
    TemporalRevision,
    TruthAssessment,
)
from aegisquant.forward import (
    ForwardHeartbeat,
    ForwardIncident,
    ForwardIncidentLog,
    ForwardModeProofReport,
    ForwardProofPolicy,
    ForwardRecoveryReceipt,
    ForwardSample,
    ForwardSession,
    PaperShadowForwardProof,
)
from aegisquant.intelligence.canonical_events import (
    CanonicalEvent,
    EventDirectionalGate,
    EventSurprise,
    EventValueSnapshot,
    MarketReflectionPolicy,
    MarketReflectionScore,
    NarrativeDiffusionObservation,
    NarrativeDiffusionSnapshot,
    TimedEventValue,
    TimedMarketReflectionMetric,
)
from aegisquant.intelligence.collectors import (
    BlueskyStreamSelection,
    CollectedContent,
    OfficialWebChangeSnapshot,
    SourceBatch,
    SourceQuotaWindow,
    SourceRequest,
)
from aegisquant.intelligence.graph import EvidenceGraph
from aegisquant.operations.live_readiness.models import (
    CanaryReleaseManifest,
    LiveReadinessPolicy,
)
from aegisquant.research.causal.contracts import (
    CausalDiagnosticPolicy,
    CausalDiagnostics,
    CausalEffectEstimate,
    CausalPointEstimate,
    CovariateBalanceReport,
    DoublyRobustObservation,
    DoublyRobustSpec,
    EventResponseDataset,
    EventResponseRow,
    EventStudySpec,
    HistoricalState,
    MatchedStateSet,
    MatchingSpec,
    PlaceboTestResult,
    PreTreatmentFitReport,
    PreTrendReport,
    PropensityOverlapReport,
    SyntheticControlResult,
    SyntheticControlSpec,
)
from aegisquant.research.forecasting import (
    AdaptiveConformalPolicy,
    AdaptiveConformalReport,
    CalibrationArtifact,
    CandidateGateDecision,
    CapabilityMatrix,
    DynamicStackingPolicy,
    EventAblationEvaluation,
    EventAblationSpec,
    EventConditionedForecast,
    EventConditionSnapshot,
    EventForecastAblationReport,
    EventForecastComparisonLineage,
    EventIncrement,
    ForecastEnvelope,
    ForecastGovernanceReport,
    ForecastInputBinding,
    IndependentSkepticAssessment,
    IntervalCoverageWindow,
    MarketOnlyForecast,
    MarketStateTensor,
    MetaReasonerRecommendation,
    ModelArenaReport,
    ModelArenaSpec,
    ModelCapability,
    OosFoldEvaluation,
    ReasoningContext,
    RegimeRoutingDecision,
    StatisticalWeightProposal,
    VisionAblationReport,
)
from aegisquant.research.provider_bakeoff.models import (
    ProviderCandidateCatalog,
    TrialPlanDocument,
)
from aegisquant.truth.calibration import (
    TruthCalibrationMetrics,
    TruthCalibrationSample,
    TruthCouncilReport,
)
from aegisquant.truth.contracts import (
    C2paVerificationResult,
    ContentAuthenticityBinding,
    ContentIntegrityAssessment,
    DetachedSignatureVerification,
    OfficialIdentityAssessment,
    OfficialIdentityObservation,
    SourceCompromiseEvent,
    SourceRegistryDocument,
)
from aegisquant.truth.features import EvidenceFeatureVector
from aegisquant.truth.lifecycle import (
    SourceReliabilitySnapshot,
    TruthModelReliabilitySnapshot,
    TruthStateTransition,
)

JSON_SCHEMA_DIALECT: Final = "https://json-schema.org/draft/2020-12/schema"


@dataclass(frozen=True, slots=True)
class Contract:
    schema_name: str
    version: str
    model: type[BaseModel]
    path: Path
    compatibility: str = "BACKWARD"


EVENT_CONTRACTS: Final = (
    Contract("aegisquant.event-envelope", "1.0.0", EventEnvelope, Path("event-envelope-v1.json")),
    Contract("aegisquant.market-event", "1.0.0", MarketEvent, Path("market-event-v1.json")),
    Contract(
        "aegisquant.raw-content-envelope",
        "1.0.0",
        RawContentEnvelope,
        Path("raw-content-envelope-v1.json"),
    ),
    Contract(
        "aegisquant.source-identity",
        "2.0.0",
        SourceIdentity,
        Path("source-identity-v2.json"),
        "MIGRATION_REQUIRED",
    ),
    Contract(
        "aegisquant.official-identity-observation",
        "1.0.0",
        OfficialIdentityObservation,
        Path("official-identity-observation-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.official-identity-assessment",
        "1.0.0",
        OfficialIdentityAssessment,
        Path("official-identity-assessment-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.detached-signature-verification",
        "1.0.0",
        DetachedSignatureVerification,
        Path("detached-signature-verification-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.c2pa-verification",
        "1.0.0",
        C2paVerificationResult,
        Path("c2pa-verification-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.content-integrity-assessment",
        "1.0.0",
        ContentIntegrityAssessment,
        Path("content-integrity-assessment-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.content-authenticity-binding",
        "1.0.0",
        ContentAuthenticityBinding,
        Path("content-authenticity-binding-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.source-compromise-event",
        "1.0.0",
        SourceCompromiseEvent,
        Path("source-compromise-event-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.evidence-search-plan",
        "1.0.0",
        EvidenceSearchPlan,
        Path("evidence-search-plan-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.evidence-retrieval-hit",
        "1.0.0",
        EvidenceRetrievalHit,
        Path("evidence-retrieval-hit-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.engagement-snapshot",
        "1.0.0",
        EngagementSnapshot,
        Path("engagement-snapshot-v1.json"),
    ),
    Contract(
        "aegisquant.collected-content",
        "1.0.0",
        CollectedContent,
        Path("collected-content-v1.json"),
    ),
    Contract("aegisquant.source-batch", "1.0.0", SourceBatch, Path("source-batch-v1.json")),
    Contract(
        "aegisquant.source-quota-window",
        "1.0.0",
        SourceQuotaWindow,
        Path("source-quota-window-v1.json"),
    ),
    Contract(
        "aegisquant.official-web-change-snapshot",
        "1.0.0",
        OfficialWebChangeSnapshot,
        Path("official-web-change-snapshot-v1.json"),
    ),
    Contract(
        "aegisquant.bluesky-stream-selection",
        "1.0.0",
        BlueskyStreamSelection,
        Path("bluesky-stream-selection-v1.json"),
    ),
    Contract("aegisquant.claim-record", "1.0.0", ClaimRecord, Path("claim-record-v1.json")),
    Contract(
        "aegisquant.atomic-claim",
        "1.0.0",
        AtomicClaim,
        Path("atomic-claim-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.truth-assessment",
        "1.0.0",
        TruthAssessment,
        Path("truth-assessment-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.evidence-feature-vector",
        "1.0.0",
        EvidenceFeatureVector,
        Path("evidence-feature-vector-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.truth-calibration-metrics",
        "1.0.0",
        TruthCalibrationMetrics,
        Path("truth-calibration-metrics-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.truth-council-report",
        "1.0.0",
        TruthCouncilReport,
        Path("truth-council-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.truth-state-transition",
        "1.0.0",
        TruthStateTransition,
        Path("truth-state-transition-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.source-reliability-snapshot",
        "1.0.0",
        SourceReliabilitySnapshot,
        Path("source-reliability-snapshot-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.truth-model-reliability-snapshot",
        "1.0.0",
        TruthModelReliabilitySnapshot,
        Path("truth-model-reliability-snapshot-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.evidence-graph",
        "1.0.0",
        EvidenceGraph,
        Path("evidence-graph-v1.json"),
        "NONE",
    ),
    Contract("aegisquant.event-cluster", "1.0.0", EventCluster, Path("event-cluster-v1.json")),
    Contract(
        "aegisquant.timed-event-value",
        "1.0.0",
        TimedEventValue,
        Path("timed-event-value-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.event-value-snapshot",
        "1.0.0",
        EventValueSnapshot,
        Path("event-value-snapshot-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.event-surprise",
        "1.0.0",
        EventSurprise,
        Path("event-surprise-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.narrative-diffusion-observation",
        "1.0.0",
        NarrativeDiffusionObservation,
        Path("narrative-diffusion-observation-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.narrative-diffusion-snapshot",
        "1.0.0",
        NarrativeDiffusionSnapshot,
        Path("narrative-diffusion-snapshot-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.timed-market-reflection-metric",
        "1.0.0",
        TimedMarketReflectionMetric,
        Path("timed-market-reflection-metric-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.market-reflection-policy",
        "1.0.0",
        MarketReflectionPolicy,
        Path("market-reflection-policy-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.market-reflection-score",
        "1.0.0",
        MarketReflectionScore,
        Path("market-reflection-score-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.canonical-event",
        "1.0.0",
        CanonicalEvent,
        Path("canonical-event-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.event-directional-gate",
        "1.0.0",
        EventDirectionalGate,
        Path("event-directional-gate-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.causal-point-estimate",
        "1.0.0",
        CausalPointEstimate,
        Path("causal-point-estimate-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.matched-state-set",
        "1.0.0",
        MatchedStateSet,
        Path("matched-state-set-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.pre-treatment-fit-report",
        "1.0.0",
        PreTreatmentFitReport,
        Path("pre-treatment-fit-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.pretrend-report",
        "1.0.0",
        PreTrendReport,
        Path("pretrend-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.covariate-balance-report",
        "1.0.0",
        CovariateBalanceReport,
        Path("covariate-balance-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.propensity-overlap-report",
        "1.0.0",
        PropensityOverlapReport,
        Path("propensity-overlap-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.placebo-test-result",
        "1.0.0",
        PlaceboTestResult,
        Path("placebo-test-result-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.causal-diagnostics",
        "1.0.0",
        CausalDiagnostics,
        Path("causal-diagnostics-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.synthetic-control-result",
        "1.0.0",
        SyntheticControlResult,
        Path("synthetic-control-result-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.causal-effect-estimate",
        "1.0.0",
        CausalEffectEstimate,
        Path("causal-effect-estimate-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.forecast-calibration-artifact",
        "1.0.0",
        CalibrationArtifact,
        Path("forecast-calibration-artifact-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.forecast-council-envelope",
        "1.0.0",
        ForecastEnvelope,
        Path("forecast-council-envelope-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.forecast-candidate-gate-decision",
        "1.0.0",
        CandidateGateDecision,
        Path("forecast-candidate-gate-decision-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.forecast-model-arena-report",
        "1.0.0",
        ModelArenaReport,
        Path("forecast-model-arena-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.forecast-vision-ablation-report",
        "1.0.0",
        VisionAblationReport,
        Path("forecast-vision-ablation-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.event-impact-forecast",
        "3.0.0",
        EventImpactForecast,
        Path("event-impact-forecast-v3.json"),
        "MIGRATION_REQUIRED",
    ),
    Contract(
        "aegisquant.v5-event-condition-snapshot",
        "1.0.0",
        EventConditionSnapshot,
        Path("v5-event-condition-snapshot-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-market-only-forecast",
        "1.0.0",
        MarketOnlyForecast,
        Path("v5-market-only-forecast-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-event-conditioned-forecast",
        "1.0.0",
        EventConditionedForecast,
        Path("v5-event-conditioned-forecast-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-event-increment",
        "1.0.0",
        EventIncrement,
        Path("v5-event-increment-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-event-forecast-ablation-report",
        "1.0.0",
        EventForecastAblationReport,
        Path("v5-event-forecast-ablation-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-meta-reasoner-recommendation",
        "1.0.0",
        MetaReasonerRecommendation,
        Path("v5-meta-reasoner-recommendation-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-independent-skeptic-assessment",
        "1.0.0",
        IndependentSkepticAssessment,
        Path("v5-independent-skeptic-assessment-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-regime-routing-decision",
        "1.0.0",
        RegimeRoutingDecision,
        Path("v5-regime-routing-decision-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-adaptive-conformal-report",
        "1.0.0",
        AdaptiveConformalReport,
        Path("v5-adaptive-conformal-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forecast-governance-report",
        "1.0.0",
        ForecastGovernanceReport,
        Path("v5-forecast-governance-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-execution-cost-distribution",
        "1.0.0",
        ExecutionCostDistribution,
        Path("v5-execution-cost-distribution-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-directional-forecast-distribution",
        "1.0.0",
        DirectionalForecastDistribution,
        Path("v5-directional-forecast-distribution-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-net-edge-distribution",
        "1.0.0",
        NetEdgeDistribution,
        Path("v5-net-edge-distribution-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-event-directional-alpha",
        "1.0.0",
        EventDirectionalAlpha,
        Path("v5-event-directional-alpha-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-event-risk-overlay",
        "1.0.0",
        EventRiskOverlay,
        Path("v5-event-risk-overlay-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-no-trade-decision",
        "1.0.0",
        NoTradeDecision,
        Path("v5-no-trade-decision-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-integrated-decision-report",
        "1.0.0",
        IntegratedDecisionReport,
        Path("v5-integrated-decision-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forward-session",
        "1.0.0",
        ForwardSession,
        Path("v5-forward-session-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forward-mode-proof-report",
        "1.0.0",
        ForwardModeProofReport,
        Path("v5-forward-mode-proof-report-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-paper-shadow-forward-proof",
        "1.0.0",
        PaperShadowForwardProof,
        Path("v5-paper-shadow-forward-proof-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-binance-testnet-run-evidence",
        "1.0.0",
        BinanceTestnetRunEvidence,
        Path("v5-binance-testnet-run-evidence-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-external-alert-delivery-receipt",
        "1.0.0",
        ExternalAlertDeliveryReceipt,
        Path("v5-external-alert-delivery-receipt-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-testnet-risk-authorization-receipt",
        "1.0.0",
        TestnetRiskAuthorizationReceipt,
        Path("v5-testnet-risk-authorization-receipt-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-p12-evidence-bundle",
        "1.0.0",
        P12EvidenceBundle,
        Path("v5-p12-evidence-bundle-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-p12-canary-readiness-assessment",
        "1.0.0",
        P12CanaryReadinessAssessment,
        Path("v5-p12-canary-readiness-assessment-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.forecast-bundle", "1.0.0", ForecastBundle, Path("forecast-bundle-v1.json")
    ),
    Contract("aegisquant.alpha-signal", "1.0.0", AlphaSignal, Path("alpha-signal-v1.json")),
    Contract(
        "aegisquant.portfolio-proposal",
        "1.0.0",
        PortfolioProposal,
        Path("portfolio-proposal-v1.json"),
    ),
    Contract("aegisquant.risk-decision", "1.0.0", RiskDecision, Path("risk-decision-v1.json")),
    Contract("aegisquant.order-intent", "1.0.0", OrderIntent, Path("order-intent-v1.json")),
    Contract("aegisquant.order-command", "1.0.0", OrderCommand, Path("order-command-v1.json")),
    Contract("aegisquant.venue-order", "1.0.0", VenueOrder, Path("venue-order-v1.json")),
    Contract("aegisquant.fill", "1.0.0", Fill, Path("fill-v1.json")),
    Contract("aegisquant.journal-entry", "1.0.0", JournalEntry, Path("journal-entry-v1.json")),
    Contract("aegisquant.position-lot", "1.0.0", PositionLot, Path("position-lot-v1.json")),
    Contract(
        "aegisquant.accounting-instrument",
        "1.0.0",
        AccountingInstrument,
        Path("accounting-instrument-v1.json"),
    ),
    Contract(
        "aegisquant.chart-of-accounts",
        "1.0.0",
        ChartOfAccounts,
        Path("chart-of-accounts-v1.json"),
    ),
    Contract(
        "aegisquant.entry-template",
        "1.0.0",
        EntryTemplate,
        Path("entry-template-v1.json"),
    ),
    Contract(
        "aegisquant.ledger-record",
        "1.0.0",
        LedgerRecord,
        Path("ledger-record-v1.json"),
    ),
    Contract(
        "aegisquant.position-lot-state",
        "1.0.0",
        PositionLotState,
        Path("position-lot-state-v1.json"),
    ),
    Contract(
        "aegisquant.cashflow-event",
        "1.0.0",
        CashflowEvent,
        Path("cashflow-event-v1.json"),
    ),
    Contract(
        "aegisquant.settlement-event",
        "1.0.0",
        SettlementEvent,
        Path("settlement-event-v1.json"),
    ),
    Contract(
        "aegisquant.valuation-snapshot",
        "1.0.0",
        ValuationSnapshot,
        Path("valuation-snapshot-v1.json"),
    ),
    Contract(
        "aegisquant.equity-snapshot",
        "1.0.0",
        EquitySnapshot,
        Path("equity-snapshot-v1.json"),
    ),
    Contract(
        "aegisquant.pnl-breakdown",
        "1.0.0",
        PnLBreakdown,
        Path("pnl-breakdown-v1.json"),
    ),
    Contract(
        "aegisquant.venue-account-snapshot",
        "1.0.0",
        VenueAccountSnapshot,
        Path("venue-account-snapshot-v1.json"),
    ),
    Contract(
        "aegisquant.reconciliation-case",
        "1.0.0",
        ReconciliationCase,
        Path("reconciliation-case-v1.json"),
    ),
    Contract(
        "aegisquant.daily-ledger-snapshot",
        "1.0.0",
        DailyLedgerSnapshot,
        Path("daily-ledger-snapshot-v1.json"),
    ),
    Contract(
        "aegisquant.backtest-run-spec",
        "1.0.0",
        BacktestRunSpec,
        Path("backtest-run-spec-v1.json"),
    ),
    Contract(
        "aegisquant.backtest-order",
        "1.0.0",
        BacktestOrder,
        Path("backtest-order-v1.json"),
    ),
    Contract(
        "aegisquant.backtest-fill",
        "1.0.0",
        BacktestFill,
        Path("backtest-fill-v1.json"),
    ),
    Contract(
        "aegisquant.backtest-result",
        "1.0.0",
        BacktestResult,
        Path("backtest-result-v1.json"),
    ),
    Contract(
        "aegisquant.backtest-cost-schedule",
        "1.0.0",
        CostSchedule,
        Path("backtest-cost-schedule-v1.json"),
    ),
    Contract(
        "aegisquant.backtest-instrument-rule",
        "1.0.0",
        HistoricalInstrumentRule,
        Path("backtest-instrument-rule-v1.json"),
    ),
    Contract(
        "aegisquant.backtest-margin-policy",
        "1.0.0",
        MarginPolicy,
        Path("backtest-margin-policy-v1.json"),
    ),
    Contract(
        "aegisquant.backtest-stress-scenario",
        "1.0.0",
        StressScenario,
        Path("backtest-stress-scenario-v1.json"),
    ),
)

CONFIG_CONTRACTS: Final = (
    Contract(
        "aegisquant.v5-p12-readiness-policy",
        "1.0.0",
        P12ReadinessPolicy,
        Path("v5-p12-readiness-policy-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forward-proof-policy",
        "1.0.0",
        ForwardProofPolicy,
        Path("v5-forward-proof-policy-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-execution-cost-model-v2",
        "1.0.0",
        ExecutionCostModelV2,
        Path("v5-execution-cost-model-v2-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-net-edge-policy",
        "1.0.0",
        NetEdgePolicy,
        Path("v5-net-edge-policy-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-risk-overlay-policy",
        "1.0.0",
        RiskOverlayPolicy,
        Path("v5-risk-overlay-policy-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-dynamic-stacking-policy",
        "1.0.0",
        DynamicStackingPolicy,
        Path("v5-dynamic-stacking-policy-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-adaptive-conformal-policy",
        "1.0.0",
        AdaptiveConformalPolicy,
        Path("v5-adaptive-conformal-policy-v1.json"),
        "NONE",
    ),
    Contract("aegisquant.app-config", "1.0.0", AppConfig, Path("app-config-v1.json")),
    Contract(
        "aegisquant.source-registry",
        "1.0.0",
        SourceRegistryDocument,
        Path("source-registry-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.backtest-policy",
        "1.0.0",
        BacktestPolicy,
        Path("backtest-policy-v1.json"),
    ),
    Contract(
        "aegisquant.causal-matching-spec",
        "1.0.0",
        MatchingSpec,
        Path("causal-matching-spec-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.causal-event-study-spec",
        "1.0.0",
        EventStudySpec,
        Path("causal-event-study-spec-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.synthetic-control-spec",
        "1.0.0",
        SyntheticControlSpec,
        Path("synthetic-control-spec-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.doubly-robust-spec",
        "1.0.0",
        DoublyRobustSpec,
        Path("doubly-robust-spec-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.causal-diagnostic-policy",
        "1.0.0",
        CausalDiagnosticPolicy,
        Path("causal-diagnostic-policy-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.source-processing-policy",
        "1.0.0",
        SourceProcessingPolicy,
        Path("source-processing-policy-domain-v1.json"),
    ),
    Contract(
        "aegisquant.provider-candidate-catalog",
        "1.0.0",
        ProviderCandidateCatalog,
        Path("provider-candidate-catalog-v1.json"),
    ),
    Contract(
        "aegisquant.provider-trial-plans",
        "1.0.0",
        TrialPlanDocument,
        Path("provider-trial-plans-v1.json"),
    ),
    Contract(
        "aegisquant.live-readiness-policy",
        "1.0.0",
        LiveReadinessPolicy,
        Path("live-readiness-policy-v1.json"),
    ),
    Contract(
        "aegisquant.canary-release-manifest",
        "1.0.0",
        CanaryReleaseManifest,
        Path("canary-release-manifest-v1.json"),
    ),
    Contract(
        "aegisquant.forecast-model-capability",
        "1.0.0",
        ModelCapability,
        Path("forecast-model-capability-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.forecast-capability-matrix",
        "1.0.0",
        CapabilityMatrix,
        Path("forecast-capability-matrix-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.forecast-model-arena-spec",
        "1.0.0",
        ModelArenaSpec,
        Path("forecast-model-arena-spec-v1.json"),
        "NONE",
    ),
)

DATA_CONTRACTS: Final = (
    Contract(
        "aegisquant.v5-protected-timestamp-receipt",
        "1.0.0",
        ProtectedTimestampReceipt,
        Path("v5-protected-timestamp-receipt-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-testnet-reconciliation-receipt",
        "1.0.0",
        TestnetReconciliationReceipt,
        Path("v5-testnet-reconciliation-receipt-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-p12-evidence-attestation",
        "1.0.0",
        P12EvidenceAttestation,
        Path("v5-p12-evidence-attestation-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-p12-gate-result",
        "1.0.0",
        P12GateResult,
        Path("v5-p12-gate-result-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forward-heartbeat",
        "1.0.0",
        ForwardHeartbeat,
        Path("v5-forward-heartbeat-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forward-sample",
        "1.0.0",
        ForwardSample,
        Path("v5-forward-sample-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forward-incident",
        "1.0.0",
        ForwardIncident,
        Path("v5-forward-incident-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forward-incident-log",
        "1.0.0",
        ForwardIncidentLog,
        Path("v5-forward-incident-log-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forward-recovery-receipt",
        "1.0.0",
        ForwardRecoveryReceipt,
        Path("v5-forward-recovery-receipt-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-replay-queue-inputs",
        "1.0.0",
        ReplayQueueInputs,
        Path("v5-replay-queue-inputs-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-execution-cost-scenario",
        "1.0.0",
        ExecutionCostScenario,
        Path("v5-execution-cost-scenario-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-directional-forecast-scenario",
        "1.0.0",
        DirectionalForecastScenario,
        Path("v5-directional-forecast-scenario-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-net-edge-scenario",
        "1.0.0",
        NetEdgeScenario,
        Path("v5-net-edge-scenario-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-reasoning-context",
        "1.0.0",
        ReasoningContext,
        Path("v5-reasoning-context-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-statistical-weight-proposal",
        "1.0.0",
        StatisticalWeightProposal,
        Path("v5-statistical-weight-proposal-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-interval-coverage-window",
        "1.0.0",
        IntervalCoverageWindow,
        Path("v5-interval-coverage-window-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-forecast-input-binding",
        "1.0.0",
        ForecastInputBinding,
        Path("v5-forecast-input-binding-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-event-forecast-comparison-lineage",
        "1.0.0",
        EventForecastComparisonLineage,
        Path("v5-event-forecast-comparison-lineage-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-event-ablation-evaluation",
        "1.0.0",
        EventAblationEvaluation,
        Path("v5-event-ablation-evaluation-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.v5-event-ablation-spec",
        "1.0.0",
        EventAblationSpec,
        Path("v5-event-ablation-spec-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.market-state-tensor",
        "1.0.0",
        MarketStateTensor,
        Path("market-state-tensor-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.forecast-oos-fold-evaluation",
        "1.0.0",
        OosFoldEvaluation,
        Path("forecast-oos-fold-evaluation-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.event-response-row",
        "1.0.0",
        EventResponseRow,
        Path("event-response-row-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.event-response-dataset",
        "1.0.0",
        EventResponseDataset,
        Path("event-response-dataset-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.historical-causal-state",
        "1.0.0",
        HistoricalState,
        Path("historical-causal-state-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.doubly-robust-observation",
        "1.0.0",
        DoublyRobustObservation,
        Path("doubly-robust-observation-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.truth-calibration-sample",
        "1.0.0",
        TruthCalibrationSample,
        Path("truth-calibration-sample-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.temporal-revision",
        "1.0.0",
        TemporalRevision,
        Path("temporal-revision-v1.json"),
        "NONE",
    ),
    Contract(
        "aegisquant.canonical-asset",
        "1.0.0",
        CanonicalAsset,
        Path("canonical-asset-v1.json"),
    ),
    Contract(
        "aegisquant.canonical-pair",
        "1.0.0",
        CanonicalPair,
        Path("canonical-pair-v1.json"),
    ),
    Contract(
        "aegisquant.canonical-exposure",
        "1.0.0",
        CanonicalExposure,
        Path("canonical-exposure-v1.json"),
    ),
    Contract(
        "aegisquant.unified-instrument",
        "1.0.0",
        UnifiedInstrument,
        Path("unified-instrument-v1.json"),
    ),
    Contract(
        "aegisquant.market-observation",
        "1.0.0",
        MarketObservation,
        Path("market-observation-v1.json"),
    ),
    Contract(
        "aegisquant.market-comparison",
        "1.0.0",
        ComparisonResult,
        Path("market-comparison-v1.json"),
    ),
    Contract(
        "aegisquant.clock-observation",
        "1.0.0",
        ClockObservation,
        Path("clock-observation-v1.json"),
    ),
    Contract(
        "aegisquant.lead-lag-observation",
        "1.0.0",
        LeadLagObservation,
        Path("lead-lag-observation-v1.json"),
    ),
    Contract(
        "aegisquant.public-exchange-request",
        "1.0.0",
        PublicRequest,
        Path("public-exchange-request-v1.json"),
    ),
    Contract(
        "aegisquant.public-ws-subscription",
        "1.0.0",
        WsSubscription,
        Path("public-ws-subscription-v1.json"),
    ),
    Contract(
        "aegisquant.public-book-update",
        "1.0.0",
        BookUpdate,
        Path("public-book-update-v1.json"),
    ),
    Contract(
        "aegisquant.public-changelog-snapshot",
        "1.0.0",
        PublicChangelogSnapshot,
        Path("public-changelog-snapshot-v1.json"),
    ),
    Contract(
        "aegisquant.source-request",
        "1.0.0",
        SourceRequest,
        Path("source-request-v1.json"),
    ),
    Contract(
        "aegisquant.provider-registry",
        "1.0.0",
        ProviderRegistryDocument,
        Path("provider-registry-v1.json"),
    ),
    Contract(
        "aegisquant.content-time-semantics",
        "1.0.0",
        ContentTimeSemantics,
        Path("content-time-semantics-v1.json"),
    ),
    Contract(
        "aegisquant.dataset-manifest",
        "1.0.0",
        DatasetManifest,
        Path("dataset-manifest-v1.json"),
    ),
    Contract(
        "aegisquant.quality-report",
        "1.0.0",
        QualityReport,
        Path("quality-report-v1.json"),
    ),
    Contract(
        "aegisquant.inventory-record",
        "1.0.0",
        InventoryRecord,
        Path("inventory-record-v1.json"),
    ),
    Contract(
        "aegisquant.import-proposal",
        "1.0.0",
        ImportProposal,
        Path("import-proposal-v1.json"),
    ),
    Contract(
        "aegisquant.ingest-checkpoint",
        "1.0.0",
        IngestCheckpoint,
        Path("ingest-checkpoint-v1.json"),
    ),
    Contract(
        "aegisquant.revision-record",
        "1.0.0",
        RevisionRecord,
        Path("revision-record-v1.json"),
    ),
    Contract(
        "aegisquant.tombstone-record",
        "1.0.0",
        TombstoneRecord,
        Path("tombstone-record-v1.json"),
    ),
    Contract(
        "aegisquant.catalog-entry",
        "1.0.0",
        CatalogEntry,
        Path("catalog-entry-v1.json"),
    ),
    Contract(
        "aegisquant.transformation-lineage",
        "1.0.0",
        TransformationLineage,
        Path("transformation-lineage-v1.json"),
    ),
    Contract(
        "aegisquant.binance-instrument-snapshot",
        "1.0.0",
        InstrumentSnapshot,
        Path("binance-instrument-snapshot-v1.json"),
    ),
    Contract(
        "aegisquant.binance-kline",
        "1.0.0",
        KlineRecord,
        Path("binance-kline-v1.json"),
    ),
    Contract(
        "aegisquant.binance-trade",
        "1.0.0",
        TradeRecord,
        Path("binance-trade-v1.json"),
    ),
    Contract(
        "aegisquant.binance-book-ticker",
        "1.0.0",
        BookTickerRecord,
        Path("binance-book-ticker-v1.json"),
    ),
    Contract(
        "aegisquant.binance-depth-delta",
        "1.0.0",
        DepthDeltaRecord,
        Path("binance-depth-delta-v1.json"),
    ),
    Contract(
        "aegisquant.binance-mark-index",
        "1.0.0",
        MarkIndexRecord,
        Path("binance-mark-index-v1.json"),
    ),
    Contract(
        "aegisquant.binance-funding-rate",
        "1.0.0",
        FundingRateRecord,
        Path("binance-funding-rate-v1.json"),
    ),
    Contract(
        "aegisquant.binance-open-interest",
        "1.0.0",
        OpenInterestRecord,
        Path("binance-open-interest-v1.json"),
    ),
    Contract(
        "aegisquant.binance-raw-response",
        "1.0.0",
        RawResponseEnvelope,
        Path("binance-raw-response-v1.json"),
    ),
    Contract(
        "aegisquant.binance-connection-health",
        "1.0.0",
        ConnectionHealth,
        Path("binance-connection-health-v1.json"),
    ),
    Contract(
        "aegisquant.binance-dataset-descriptor",
        "1.0.0",
        DatasetDescriptor,
        Path("binance-dataset-descriptor-v1.json"),
    ),
    Contract(
        "aegisquant.binance-provider-health",
        "1.0.0",
        ProviderHealth,
        Path("binance-provider-health-v1.json"),
    ),
    Contract(
        "aegisquant.binance-provider-quota",
        "1.0.0",
        ProviderQuota,
        Path("binance-provider-quota-v1.json"),
    ),
    Contract(
        "aegisquant.binance-fixture-envelope",
        "1.0.0",
        FixtureEnvelope,
        Path("binance-fixture-envelope-v1.json"),
    ),
    Contract(
        "aegisquant.binance-fixture-manifest",
        "1.0.0",
        FixtureManifest,
        Path("binance-fixture-manifest-v1.json"),
    ),
    Contract(
        "aegisquant.binance-changelog-snapshot",
        "1.0.0",
        ChangelogSnapshot,
        Path("binance-changelog-snapshot-v1.json"),
    ),
    Contract(
        "aegisquant.binance-soak-stream-evidence",
        "1.0.0",
        SoakStreamEvidence,
        Path("binance-soak-stream-evidence-v1.json"),
    ),
    Contract(
        "aegisquant.binance-soak-evidence",
        "1.0.0",
        SoakEvidence,
        Path("binance-soak-evidence-v1.json"),
    ),
)


def schema_bytes(contract: Contract) -> bytes:
    schema = contract.model.model_json_schema(mode="validation")
    schema["$schema"] = JSON_SCHEMA_DIALECT
    schema["$id"] = f"https://aegisquant.local/schemas/{contract.schema_name}/{contract.version}"
    schema["x-aegisquant-schema-name"] = contract.schema_name
    schema["x-aegisquant-schema-version"] = contract.version
    return (json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode()


def expected_outputs(root: Path) -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    registry_entries: list[dict[str, str]] = []
    for directory, contracts in (
        (root / "schemas/events", EVENT_CONTRACTS),
        (root / "schemas/config", CONFIG_CONTRACTS),
    ):
        for contract in contracts:
            path = directory / contract.path
            raw = schema_bytes(contract)
            outputs[path] = raw
            registry_entries.append(
                {
                    "schema_name": contract.schema_name,
                    "schema_version": contract.version,
                    "model": f"{contract.model.__module__}.{contract.model.__name__}",
                    "path": path.relative_to(root).as_posix(),
                    "sha256": hashlib.sha256(raw).hexdigest(),
                    "compatibility": contract.compatibility,
                }
            )
    registry = {
        "schema_version": "1.0.0",
        "event_contracts": registry_entries,
    }
    outputs[root / "schemas/events/registry.json"] = (
        json.dumps(registry, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode()
    data_registry_entries: list[dict[str, str]] = []
    for contract in DATA_CONTRACTS:
        path = root / "schemas/data" / contract.path
        raw = schema_bytes(contract)
        outputs[path] = raw
        data_registry_entries.append(
            {
                "schema_name": contract.schema_name,
                "schema_version": contract.version,
                "model": f"{contract.model.__module__}.{contract.model.__name__}",
                "path": path.relative_to(root).as_posix(),
                "sha256": hashlib.sha256(raw).hexdigest(),
                "compatibility": contract.compatibility,
            }
        )
    data_registry = {
        "schema_version": "1.0.0",
        "data_contracts": data_registry_entries,
    }
    outputs[root / "schemas/data/registry.json"] = (
        json.dumps(data_registry, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode()
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    outputs = expected_outputs(root)
    if args.check:
        stale = [
            path for path, raw in outputs.items() if not path.is_file() or path.read_bytes() != raw
        ]
        if stale:
            raise SystemExit(f"generated schemas are stale: {[path.as_posix() for path in stale]}")
        print(f"verified {len(outputs)} generated schema artifacts")
        return 0
    for path, raw in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(raw)
    print(f"wrote {len(outputs)} generated schema artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
